name: Release

on:
  release:
    types: [published,] # 表示在创建新的 Release 时触发

jobs:
  # the workflow can contain other jobs, such as linting, testing, etc.
  release:
    runs-on: ubuntu-latest
    steps:
      # run git checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

      # run goreleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
          distribution: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}